PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE ucs
        (
            id                  unique primary key,
            subjectName         varchar(50),
            category            varchar(50),
            chTotal             int,
            requirements        varchar(300),
            semesterAvailable   varchar(25)
        );
INSERT INTO ucs VALUES('1','Álgebra Linear','Eletiva',72,'Geometria Analítica','IMPAR');
INSERT INTO ucs VALUES('2','Álgebra Linear Computacional','Eletiva',72,'Cálculo Numérico','IMPAR');
INSERT INTO ucs VALUES('3','Álgebra Linear II','Eletiva',72,'Álgebra Linear','nan');
INSERT INTO ucs VALUES('4','Algoritmos e Estruturas de Dados I','Eletiva',72,'Lógica de Programação','nan');
INSERT INTO ucs VALUES('5','Algoritmos e Estruturas de Dados II','Eletiva',72,'Algoritmos e Estruturas de Dados I','IMPAR');
INSERT INTO ucs VALUES('6','Algoritmos em Bioinformática','Interdisciplinar',72,'Lógica de Programação','nan');
INSERT INTO ucs VALUES('7',replace('Alteridade e Diversidade no Brasil: Implicações para Política de Ciência e\nTecnologia','\n',char(10)),'Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('8','Análise de Investimentos e Riscos','Interdisciplinar',72,'Cálculo em Uma Variável','nan');
INSERT INTO ucs VALUES('9','Análise de Sinais','Eletiva',72,'Séries e Equações Diferenciais Ordinárias','IMPAR');
INSERT INTO ucs VALUES('10','Análise do Rn','Eletiva',72,'Cálculo em Várias Variáveis; Análise Real I','nan');
INSERT INTO ucs VALUES('11','Análise Multivariada','Eletiva',72,'Inferência e Análise de Regressão; Probabilidade','nan');
INSERT INTO ucs VALUES('12','Análise Real I','Eletiva',72,'Cálculo em Uma Variável','IMPAR');
INSERT INTO ucs VALUES('13','Análise Real II','Eletiva',72,'Análise Real I','nan');
INSERT INTO ucs VALUES('14','Anatomia','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('15','Aprendizado de Máquina e Reconhecimento de Padrões','Eletiva',72,'Probabilidade e Estatística; Lógica de Programação','nan');
INSERT INTO ucs VALUES('16','Arquitetura e Organização de Computadores','Eletiva',72,'Circuitos Digitais','nan');
INSERT INTO ucs VALUES('17','Aspectos de Implementação de Banco de Dados','Eletiva',72,'Banco de Dados','IMPAR');
INSERT INTO ucs VALUES('18','Avanços em Engenharia Biomédica','Eletiva',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('19','Banco de Dados','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('20','Bioengenharia','Eletiva',72,'Fisiologia Humana','IMPAR');
INSERT INTO ucs VALUES('21','Bioestatística','Interdisciplinar',72,'Cálculo em Uma Variável','nan');
INSERT INTO ucs VALUES('22','Bioética e Biossegurança','Interdisciplinar',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('23','Biofísica','Eletiva',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('24','Bioinformática Avançada','Eletiva',72,'Introdução à Bioinformática','nan');
INSERT INTO ucs VALUES('25','Biologia do Desenvolvimento','Eletiva',36,'Biologia Molecular do Gene','IMPAR');
INSERT INTO ucs VALUES('26','Biologia Estrutural','Eletiva',72,'Bioquímica I','nan');
INSERT INTO ucs VALUES('27','Biologia Geral','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('28','Biologia Molecular da Célula','Eletiva',72,'Fundamentos de Biologia Moderna','IMPAR');
INSERT INTO ucs VALUES('29','Biologia Molecular do Gene','Eletiva',72,'Fundamentos de Biologia Moderna','nan');
INSERT INTO ucs VALUES('30','Biomateriais','Interdisciplinar',36,'Química Geral','IMPAR');
INSERT INTO ucs VALUES('31','Biomecânica','Eletiva',72,'Sistemas Mecânicos.','IMPAR');
INSERT INTO ucs VALUES('32','Bioquímica Analítica','Eletiva',72,'Bioquímica I','IMPAR');
INSERT INTO ucs VALUES('33','Bioquímica I','Eletiva',72,'Fundamentos de Biologia Moderna','nan');
INSERT INTO ucs VALUES('34','Bioquímica II','Eletiva',72,'Bioquímica I','nan');
INSERT INTO ucs VALUES('35','Biossensores','Eletiva',72,replace('QuímicaGeral;FenômenosEletromagnéticos;FundamentosdeBiologia\nModerna','\n',char(10)),'nan');
INSERT INTO ucs VALUES('36','Biotecnologia Ambiental I','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('37','Biotecnologia Ambiental II','Eletiva',72,'Biotecnologia Ambiental I','IMPAR');
INSERT INTO ucs VALUES('38','Biotecnologia Animal','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('39','Biotecnologia de Energias Renováveis I','Eletiva',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('40','Biotecnologia de Energias Renováveis II','Eletiva',72,'Biotecnologia de energias renováveis II','nan');
INSERT INTO ucs VALUES('41','Biotecnologia Vegetal','Eletiva',72,'Botânica e Fisiologia Vegetal','IMPAR');
INSERT INTO ucs VALUES('42','Botânica e Fisiologia Vegetal','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('43','Cálculo em Uma Variável','Fixa',108,'Não há','nan');
INSERT INTO ucs VALUES('44','Cálculo em Várias Variáveis','Eletiva',72,'Cálculo em Uma Variável; Geometria Analítica','IMPAR');
INSERT INTO ucs VALUES('45','Cálculo Numérico','Eletiva',72,'Cálculo em Uma Variável;  Geometria Analítica','nan');
INSERT INTO ucs VALUES('46','Cálculo Variacional','Eletiva',72,'Séries e Equações Diferenciais Ordinárias; Cálculo em Várias Variáveis','nan');
INSERT INTO ucs VALUES('47','Cerâmicas Refratárias','Eletiva',36,'Materiais Cerâmicos','nan');
INSERT INTO ucs VALUES('48','Cidadania, Ciência e Polêmica','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('49','Ciência e Tecnologia dos Materiais','Eletiva',72,'Química Geral','nan');
INSERT INTO ucs VALUES('50','Ciência, Tecnologia e Sociedade','Fixa',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('51','Ciência, Tecnologia, Sociedade e Ambiente','Fixa',36,'Não há','nan');
INSERT INTO ucs VALUES('52','Circuitos Digitais','Eletiva',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('53','Circuitos Elétricos I','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('54','Circuitos Elétricos II','Eletiva',72,'Circuitos Elétricos I; Fenômenos Eletromagnéticos','IMPAR');
INSERT INTO ucs VALUES('55','Classificação de Sinais Biológicos','Eletiva',36,'Lógica de Programação; Análise de Sinais','nan');
INSERT INTO ucs VALUES('56','Códigos Corretores de Erros','Interdisciplinar',72,'Álgebra Linear','nan');
INSERT INTO ucs VALUES('57','Combinatória Enumerativa','Eletiva',72,'Matemática Discreta','nan');
INSERT INTO ucs VALUES('58','Compiladores','Eletiva',72,'Linguagens Formais e Autômatos','nan');
INSERT INTO ucs VALUES('59','Computação Bioinspirada','Interdisciplinar',72,'Algoritmos e Estrutura de Dados I','nan');
INSERT INTO ucs VALUES('60','Computação Gráfica','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('61','Controle de Sistemas Dinâmicos','Eletiva',72,'Séries e Equações Diferenciais Ordinárias; Análise de Sinais','nan');
INSERT INTO ucs VALUES('62','Corrosão e Degradação de Materiais','Eletiva',72,'Ciência e Tecnologia dos Materiais','IMPAR');
INSERT INTO ucs VALUES('63','Cultura Digital','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('64','Cultura dos Jogos Digitais','Interdisciplinar',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('65','Desenho Técnico Assistido por Computador','Eletiva',36,'Desenho Técnico Básico','nan');
INSERT INTO ucs VALUES('66','Desenho Técnico Básico','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('67','Desenvolvimento de Aplicações Robóticas','Eletiva',72,'Algoritmos e Estrutura de Dados I','nan');
INSERT INTO ucs VALUES('68','Direitos Humanos, Multiculturalismo e C&T','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('69','Ecologia Avançada','Eletiva',72,'Introdução à Ecologia','nan');
INSERT INTO ucs VALUES('70','Econometria','Eletiva',72,'Cálculo em Várias Variáveis, Probabilidade e Estatística','nan');
INSERT INTO ucs VALUES('71','Economia Matemática','Interdisciplinar',72,'Cálculo em Uma Variável','nan');
INSERT INTO ucs VALUES('72','Economia Monetária e Bancos','Eletiva',36,'Cálculo em Várias Variáveis; Probabilidade e Estatística','nan');
INSERT INTO ucs VALUES('73','Economia, Sociedade e Ambiente','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('74','Elaboração de Trabalhos Científicos e Tecnológicos em Computação','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('75','Elementos de Álgebra','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('76','Eletrônica Avançada','Eletiva',72,'Circuitos Elétricos II','nan');
INSERT INTO ucs VALUES('77','Empreendedorismo em Biotecnologia','Interdisciplinar',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('78','Engenharia Bioquímica I','Eletiva',72,'Fundamentos de Engenharia Bioquímica; Microbiologia Geral','IMPAR');
INSERT INTO ucs VALUES('79','Engenharia Bioquímica II','Eletiva',72,'Engenharia Bioquímica I','nan');
INSERT INTO ucs VALUES('80','Engenharia Cerâmica','Eletiva',72,'Processamento de Materiais Cerâmicos','nan');
INSERT INTO ucs VALUES('81','Engenharia Clínica Hospitalar Aplicada','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('82','Engenharia de Software','Eletiva',72,'Programação Orientada a Objetos','nan');
INSERT INTO ucs VALUES('83','Engenharia Médica Aplicada','Eletiva',72,replace('Fisiologia Humana; Análise de Sinais; Imagens Biomédicas; Transdução de\nGrandezas Biomédicas','\n',char(10)),'nan');
INSERT INTO ucs VALUES('84','Engenharia Tecidual e Biofabricação','Eletiva',36,'Fisiologia Humana','nan');
INSERT INTO ucs VALUES('85','Engenharia Tecidual e Medicina Regenerativa','Interdisciplinar',72,'Biologia Molecular da Célula; Fisiologia Humana','nan');
INSERT INTO ucs VALUES('86','Ensaios de Materiais','Eletiva',72,'Ciência e Tecnologia dos Materiais','nan');
INSERT INTO ucs VALUES('87','Equações Diferenciais Ordinárias','Eletiva',72,'Álgebra Linear; Séries e Equações Diferenciais Ordinárias','nan');
INSERT INTO ucs VALUES('88','Equações Diferenciais Parciais','Eletiva',72,'Cálculo em Várias Variáveis; Séries e Equações Diferenciais Ordinárias','IMPAR');
INSERT INTO ucs VALUES('89','Espaços Métricos','Eletiva',72,'Cálculo em Várias Variáveis','IMPAR');
INSERT INTO ucs VALUES('90','Estatística Matemática','Eletiva',72,'Probabilidade','nan');
INSERT INTO ucs VALUES('91','Estrutura e Propriedades de Polímeros','Eletiva',72,'Materiais Poliméricos','nan');
INSERT INTO ucs VALUES('92','Farmacologia Molecular','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('93','Fenômenos de Transporte','Eletiva',72,'Séries e Equações Diferenciais Ordinárias; Mecânica Geral','IMPAR');
INSERT INTO ucs VALUES('94','Fenômenos do Contínuo','Eletiva',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('95','Fenômenos do Contínuo Experimental','Eletiva',36,'Não Há','nan');
INSERT INTO ucs VALUES('96','Fenômenos Eletromagnéticos','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('97','Fenômenos Eletromagnéticos Experimental','Eletiva',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('98','Fenômenos Mecânicos','Fixa',72,'Não há','nan');
INSERT INTO ucs VALUES('99','Fenômenos Mecânicos Experimental','Eletiva',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('100','Física Geral','Eletiva',72,'Fenômenos Mecânicos','IMPAR');
INSERT INTO ucs VALUES('101','Física Moderna','Eletiva',72,replace('FenômenosMecânicos;FenômenosdoContínuo;Fenômenos\nEletromagnéticos','\n',char(10)),'IMPAR');
INSERT INTO ucs VALUES('102','Física Moderna Experimental','Eletiva',72,replace('FenômenosMecânicos;FenômenosdoContínuo;Fenômenos\nEletromagnéticos Experimental','\n',char(10)),'nan');
INSERT INTO ucs VALUES('103','Fisiologia Experimental','Eletiva',72,'Fisiologia Humana','nan');
INSERT INTO ucs VALUES('104','Fisiologia Humana','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('105','Fisiopatologia Cardiorrespiratória','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('106','Fisiopatologia Clínica dos Sistemas Humanos','Eletiva',72,'Fisiologia Humana','nan');
INSERT INTO ucs VALUES('107','Fluxos em Redes','Interdisciplinar',72,'Otimização Linear','nan');
INSERT INTO ucs VALUES('108','Funções Analíticas','Eletiva',72,'Cálculo em Várias Variáveis; Séries e Equações Diferenciais Ordinárias','nan');
INSERT INTO ucs VALUES('109','Fundamentos de Biologia Moderna','Fixa',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('110','Fundamentos de Engenharia Bioquímica','Eletiva',72,'Matemática Geral; Física Geral','nan');
INSERT INTO ucs VALUES('111','Fundamentos de Matlab Aplicado à Engenharia','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('112','Fundamentos de Mecânica Celeste','Interdisciplinar',72,'Fenômenos Mecânicos; Séries e Equações Diferenciais Ordinárias','nan');
INSERT INTO ucs VALUES('113','Fundamentos de Metalurgia I','Eletiva',72,'Ciência e Tecnologia dos Materiais','nan');
INSERT INTO ucs VALUES('114','Fundamentos de Metalurgia II','Eletiva',72,'Ciência e Tecnologia dos Materiais; Resistência dos Materiais','nan');
INSERT INTO ucs VALUES('115','Geometria Analítica','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('116','Gestão de Projetos','Eletiva',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('117','Imagens Biomédicas','Eletiva',72,'Análise de Sinais','IMPAR');
INSERT INTO ucs VALUES('118','Imunologia Aplicada','Eletiva',72,'Imunologia Geral','nan');
INSERT INTO ucs VALUES('119','Imunologia Geral','Eletiva',72,'Biologia Molecular da Célula','IMPAR');
INSERT INTO ucs VALUES('120','Inferência e Análise de Regressão','Eletiva',72,'Probabilidade','nan');
INSERT INTO ucs VALUES('121','Instrumentos Biomédicos I','Eletiva',72,'Circuitos Elétricos II','nan');
INSERT INTO ucs VALUES('122','Instrumentos Biomédicos II','Eletiva',72,'Circuitos Elétricos II','nan');
INSERT INTO ucs VALUES('123','Inteligência Artificial','Eletiva',72,'Algoritmos e Estruturas de Dados I','IMPAR');
INSERT INTO ucs VALUES('124','Interação Humano-Computador','Eletiva',72,'Programação Orientada a Objetos','nan');
INSERT INTO ucs VALUES('125','Introdução  à Ecologia','Interdisciplinar',72,'Não há','nan');
INSERT INTO ucs VALUES('126','Introdução à Aeroelasticidade','Interdisciplinar',72,'Fenômenos Mecânicos; Cálculo Numérico','nan');
INSERT INTO ucs VALUES('127','Introdução à Análise Funcional','Eletiva',72,'Análise Real II','nan');
INSERT INTO ucs VALUES('128','Introdução à Bioinformática','Interdisciplinar',72,'Biologia Molecular da Célula; Lógica de Programação','IMPAR');
INSERT INTO ucs VALUES('129','Introdução à Biologia de Sistemas','Interdisciplinar',72,'Biologia Molecular da Célula','nan');
INSERT INTO ucs VALUES('130','Introdução à Biotecnologia','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('131','Introdução à Economia Global','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('132','Introdução à Eletrotécnica','Eletiva',36,'Circuitos Elétricos II','nan');
INSERT INTO ucs VALUES('133','Introdução à Engenharia Biomédica','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('134','Introdução à Engenharia de Materiais','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('135','Introdução à Engenharia Financeira','Eletiva',72,'Cálculo em Várias Variáveis; Probabilidade e Estatística','nan');
INSERT INTO ucs VALUES('136','Introdução à Geometria Diferencial','Eletiva',72,'Cálculo em Várias Variáveis','nan');
INSERT INTO ucs VALUES('137','Introdução à Lógica Fuzzy','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('138','Introdução à Nanotecnologia','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('139','Introdução à Pesquisa Operacional','Eletiva',72,'Álgebra Linear','nan');
INSERT INTO ucs VALUES('140','Introdução às Redes Neurais Artificiais','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('141','Laboratório de Biologia Molecular e Celular','Interdisciplinar',36,'Biologia Molecular da Célula','nan');
INSERT INTO ucs VALUES('142','Laboratório de Bioquímica','Interdisciplinar',72,'Bioquímica I; Biologia Molecular do Gene','IMPAR');
INSERT INTO ucs VALUES('143','Laboratório de Bioquímica Analítica','Eletiva',36,'Bioquímica Analítica','nan');
INSERT INTO ucs VALUES('144','Laboratório de Circuitos Elétricos','Eletiva',36,'Fenômenos Eletromagnéticos; Circuitos Elétricos I','IMPAR');
INSERT INTO ucs VALUES('145','Laboratório de Eletrônica Digital','Eletiva',36,'Circuitos Digitais','nan');
INSERT INTO ucs VALUES('146','Laboratório de Engenharia Bioquímica','Interdisciplinar',36,'Engenharia Bioquímica I','nan');
INSERT INTO ucs VALUES('147','Laboratório de Estatística Aplicada','Eletiva',72,'Inferência e Análise de Regressão; Probabilidade','nan');
INSERT INTO ucs VALUES('148','Laboratório de Microbiologia','Interdisciplinar',36,'Microbiologia Geral','nan');
INSERT INTO ucs VALUES('149','Laboratório de Sistemas Computacionais: Arquitetura e Organização de Computadores','Eletiva',72,' Arquitetura e Organização de Computadores; Laboratório de Sistemas Computacionais: Circuitos Digitais','IMPAR');
INSERT INTO ucs VALUES('150','Laboratório de Sistemas Computacionais: Circuitos Digitais','Eletiva',36,'Circuitos Digitais','nan');
INSERT INTO ucs VALUES('151','Laboratório de Sistemas Computacionais: Compiladores','Eletiva',72,'Compiladores;Laboratório de Sistemas Computacionais: Engenharia de Sistemas','IMPAR');
INSERT INTO ucs VALUES('152','Laboratório de Sistemas Computacionais: Redes de Computadores','Eletiva',36,'Redes de Computadores;Laboratório de Sistemas Computacionais: Sistemas Operacionais','nan');
INSERT INTO ucs VALUES('153','Laboratório de Sistemas Computacionais: Sistemas Operacionais','Eletiva',72,'Sistemas Operacionais;Laboratório de Sistemas Computacionais: Sistemas Operacionais','nan');
INSERT INTO ucs VALUES('154','Laboratório de Usabilidade na Web','Eletiva',72,'Programação Orientada a Objetos','nan');
INSERT INTO ucs VALUES('155','Legislação Ambiental e Políticas Públicas','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('156','Linguagens Formais e Autômatos','Eletiva',72,'Matemática Discreta; Lógica de Programação','nan');
INSERT INTO ucs VALUES('157','Lógica de Programação','Fixa',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('158','Macroeconomia','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('159','Matemática Discreta','Eletiva',72,'não há','nan');
INSERT INTO ucs VALUES('160','Matemática Geral','Eletiva',72,'Cálculo em Uma Variável','nan');
INSERT INTO ucs VALUES('161','Materiais Cerâmicos','Eletiva',72,'Ciência e Tecnologia dos Materiais','IMPAR');
INSERT INTO ucs VALUES('162','Materiais Compósitos','Eletiva',72,'Ciência e Tecnologia de Materiais','nan');
INSERT INTO ucs VALUES('163','Materiais Elétricos','Eletiva',72,'Fenômenos Eletromagnéticos','IMPAR');
INSERT INTO ucs VALUES('164','Materiais Metálicos','Eletiva',72,'Ciência e Tecnologia dos Materiais','IMPAR');
INSERT INTO ucs VALUES('165','Materiais Poliméricos','Eletiva',72,'Ciência e Tecnologia de Materiais','IMPAR');
INSERT INTO ucs VALUES('166','Matérias-Primas Cerâmicas','Eletiva',72,'Materiais Cerâmicos','nan');
INSERT INTO ucs VALUES('167','Mecânica da Fratura','Eletiva',72,'Fundamentos de Metalurgia II','nan');
INSERT INTO ucs VALUES('168','Mecânica Geral','Eletiva',72,'Geometria Analítica; Fenômenos Mecânicos','IMPAR');
INSERT INTO ucs VALUES('169','Metalurgia do Pó','Eletiva',36,'Fundamentos de Metalurgia I','IMPAR');
INSERT INTO ucs VALUES('170','Metalurgia Extrativa','Eletiva',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('171','Metodologia da Pesquisa e Comunicação Científica','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('172','Métodos Avançados em Processamento de Imagens Biomédicas','Eletiva',72,'Análise de Sinais','nan');
INSERT INTO ucs VALUES('173','Métodos Matemáticos','Eletiva',72,'Cálculo em Várias Variáveis; Séries e Equações Diferencias Ordinárias','nan');
INSERT INTO ucs VALUES('174','Métodos Numéricos para Equações Diferenciais','Interdisciplinar',72,'Cálculo Numérico; Álgebra Linear; Séries e Equações Diferenciais Ordinárias','nan');
INSERT INTO ucs VALUES('175','Métodos Probabilísticos em Pesquisa Operacional','Interdisciplinar',72,'Probabilidade e Estatística; Otimização Linear','nan');
INSERT INTO ucs VALUES('176','Microbiologia Aplicada e Industrial','Eletiva',72,'Microbiologia Geral','IMPAR');
INSERT INTO ucs VALUES('177','Microbiologia Geral','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('178','Microeconomia','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('179','Modelagem Computacional','Interdisciplinar',36,'Lógica de Programação; Cálculo em Uma Variável','IMPAR');
INSERT INTO ucs VALUES('180','Modelagem Molecular','Eletiva',72,'Biologia Estrutural','IMPAR');
INSERT INTO ucs VALUES('181','Modelos Animais','Eletiva',72,'Biotecnologia Animal','IMPAR');
INSERT INTO ucs VALUES('182','Modelos Lineares Generalizados','Eletiva',72,'Probabilidade','nan');
INSERT INTO ucs VALUES('183','Mudança do Clima e Sociedade','Interdisciplinar',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('184','Multimídia','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('185','Operações Unitárias','Eletiva',72,'Fenômenos de Transporte','nan');
INSERT INTO ucs VALUES('186','Organização Industrial','Eletiva',36,'Cálculo em Várias Variáveis','nan');
INSERT INTO ucs VALUES('187','Otimização Inteira','Interdisciplinar',72,'Otimização Linear','nan');
INSERT INTO ucs VALUES('188','Otimização Linear','Eletiva',72,'Geometria Analítica; Lógica de Programação','nan');
INSERT INTO ucs VALUES('189','Otimização Não Linear','Eletiva',72,'Cálculo em Várias Variáveis; Cálculo Numérico','nan');
INSERT INTO ucs VALUES('190','Paradigmas de Programação','Eletiva',72,'Programação Orientada a Objetos','nan');
INSERT INTO ucs VALUES('191','Planejamento de Experimentos','Eletiva',36,'Probabilidade e Estatística','nan');
INSERT INTO ucs VALUES('192','Política Científica e Tecnológica (PC&T)','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('193','Probabilidade','Eletiva',72,'Probabilidade e Estatística; Cálculo em Várias Variáveis','nan');
INSERT INTO ucs VALUES('194','Probabilidade e Estatística','Interdisciplinar',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('195','Processamento de Imagens','Eletiva',72,'Algoritmos e Estruturas de Dados I; Séries e Equações Diferenciais Ordinárias','nan');
INSERT INTO ucs VALUES('196','Processamento de Materiais','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('197','Processamento de Materiais Cerâmicos','Eletiva',72,'Materiais Cerâmicos','nan');
INSERT INTO ucs VALUES('198','Processamento de Materiais Metálicos','Eletiva',72,'Fundamentos de Metalurgia I; Fundamentos de Metalurgia II','IMPAR');
INSERT INTO ucs VALUES('199','Processamento de Sinais Biomédicos','Eletiva',72,'Análise de Sinais','nan');
INSERT INTO ucs VALUES('200','Processamento de Termofixos e Elastômeros','Eletiva',36,'Materiais Poliméricos','nan');
INSERT INTO ucs VALUES('201','Processamento de Termoplásticos','Eletiva',72,'Materiais Poliméricos','IMPAR');
INSERT INTO ucs VALUES('202','Processos Estocásticos','Eletiva',72,'Probabilidade','nan');
INSERT INTO ucs VALUES('203','Programação Concorrente e Distribuída','Eletiva',72,'Sistemas Operacionais','nan');
INSERT INTO ucs VALUES('204','Programação Orientada a Objetos','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('205','Programação Paralela e Processamento de Alto Desempenho','Eletiva',72,'Programação Concorrente e Distribuída','nan');
INSERT INTO ucs VALUES('206','Projeto de Sistemas Digitais','Eletiva',72,'Lógica de Programação; Arquitetura e Organização de Computadores','nan');
INSERT INTO ucs VALUES('207','Projeto e Análise de Algoritmos','Eletiva',72,'Matemática Discreta; Algoritmos e Estruturas de Dados II','nan');
INSERT INTO ucs VALUES('208','Projeto Orientado a Objetos','Eletiva',72,'Programação Orientada a Objetos','IMPAR');
INSERT INTO ucs VALUES('209','Projetos em Engenharia de Computação','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('210','Propriedades e Produtos Cerâmicos','Eletiva',72,'Materiais Cerâmicos','nan');
INSERT INTO ucs VALUES('211','Proteômica','Eletiva',72,'Bioquímica Analítica; Introdução à Bioinformática','nan');
INSERT INTO ucs VALUES('212','Qualidade','Eletiva',36,'Probabilidade e Estatística','nan');
INSERT INTO ucs VALUES('213','Química Analítica','Eletiva',72,'Química Geral; Química Geral Experimental','nan');
INSERT INTO ucs VALUES('214','Química Geral','Fixa',72,'Não há','IMPAR');
INSERT INTO ucs VALUES('215','Química Geral Experimental','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('216','Química Inorgânica','Eletiva',72,'Química Geral','IMPAR');
INSERT INTO ucs VALUES('217','Química Medicinal I','Eletiva',72,'Bioquímica I','nan');
INSERT INTO ucs VALUES('218','Química Medicinal II','Eletiva',72,'Química Medicinal I','nan');
INSERT INTO ucs VALUES('219','Química Orgânica','Eletiva',72,'Química Geral','IMPAR');
INSERT INTO ucs VALUES('220','Química Orgânica Experimental','Eletiva',72,'Química Geral; Química Geral Experimental','nan');
INSERT INTO ucs VALUES('221','Realidade Virtual e Aumentada','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('222','Recuperação de Informação Multimídia','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('223','Redes de Computadores','Eletiva',72,'Programação Orientada a Objetos','nan');
INSERT INTO ucs VALUES('224','Relações Étnico-Raciais e Cultura Afro-Brasileira e Indígena','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('225','Reologia dos Materiais','Eletiva',36,'Materiais Poliméricos; Ciência e Tecnologia dos Materiais','IMPAR');
INSERT INTO ucs VALUES('226','Resistência dos Materiais','Eletiva',72,'Mecânica Geral','IMPAR');
INSERT INTO ucs VALUES('227','Segurança Computacional','Eletiva',72,'Sistemas Operacionais','IMPAR');
INSERT INTO ucs VALUES('228','Seleção de Materiais','Interdisciplinar',36,'Ciência e Tecnologia dos Materiais.','nan');
INSERT INTO ucs VALUES('229','Seminários Interdisciplinares','Eletiva',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('230','Séries e Equações Diferenciais Ordinárias','Eletiva',72,'Cálculo em Uma Variável','nan');
INSERT INTO ucs VALUES('231','Séries Temporais e Previsões','Interdisciplinar',72,'Inferência e Análise de Regressão','nan');
INSERT INTO ucs VALUES('232','Simulação de Sistemas','Interdisciplinar',72,'Lógica de Programação; Probabilidade','nan');
INSERT INTO ucs VALUES('233','Síntese de Polímeros','Eletiva',72,'Química Orgânica','IMPAR');
INSERT INTO ucs VALUES('234','Sistemas Distribuídos','Eletiva',72,'Sistemas Operacionais','nan');
INSERT INTO ucs VALUES('235','Sistemas Embarcados','Eletiva',72,replace('AlgoritmoseEstruturasdeDadosI;ArquiteturaeOrganizaçãode\nComputadores','\n',char(10)),'IMPAR');
INSERT INTO ucs VALUES('236','Sistemas Mecânicos','Eletiva',72,'Mecânica Geral','nan');
INSERT INTO ucs VALUES('237','Sistemas Operacionais','Eletiva',72,'Algoritmos e Estruturas de Dados I','IMPAR');
INSERT INTO ucs VALUES('238','Sistemas Robóticos','Eletiva',72,'Algoritmos e Estruturas de Dados I; Fenômenos Mecânicos','nan');
INSERT INTO ucs VALUES('239','Técnicas Experimentais','Eletiva',72,'Ciência e Tecnologia dos Materiais','IMPAR');
INSERT INTO ucs VALUES('240','Tecnologia e Meio Ambiente','Interdisciplinar',36,'Não há','IMPAR');
INSERT INTO ucs VALUES('241','Tecnologia em Tintas e Vernizes','Eletiva',36,'Materiais Poliméricos','nan');
INSERT INTO ucs VALUES('242','Tecnologia Social: Práxis e Contra-Hegemonia','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('243','Tecnologias Assistivas','Eletiva',72,'Anatomia; Fisiologia Humana','nan');
INSERT INTO ucs VALUES('244','Teoria das Finanças','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('245','Teoria dos Grafos','Eletiva',72,'Projeto e Análise de Algoritmos','IMPAR');
INSERT INTO ucs VALUES('246','Teoria dos Números e Criptografia','Interdisciplinar',72,'Matemática Discreta','IMPAR');
INSERT INTO ucs VALUES('247','Teorias Administrativas','Eletiva',36,'Não há','nan');
INSERT INTO ucs VALUES('248','Termodinâmica dos Sólidos','Eletiva',72,'Química Geral','nan');
INSERT INTO ucs VALUES('249','Termodinâmica Química','Eletiva',72,'Química Geral; Cálculo em Uma Variável','nan');
INSERT INTO ucs VALUES('250','Tópicos em Ciência e Tecnologia I','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('251','Tópicos em Ciência e Tecnologia II','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('252','Tópicos em Ciência e Tecnologia III','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('253','Tópicos em Ciência e Tecnologia IV','Interdisciplinar',36,'Não há','nan');
INSERT INTO ucs VALUES('254','Tópicos em Fundamentos da Computação I','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('255','Tópicos em Fundamentos da Computação II','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('256','Tópicos em Matemática Computacional I','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('257','Tópicos em Matemática Computacional II','Eletiva',72,'Não há','nan');
INSERT INTO ucs VALUES('258','Tópicos em Tecnologia da Computação I','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('259','Tópicos em Tecnologia da Computação II','Eletiva',72,'Algoritmos e Estruturas de Dados I','nan');
INSERT INTO ucs VALUES('260','Tópicos Interdisciplinares em Computação I','Interdisciplinar',36,'Lógica de Programação','nan');
INSERT INTO ucs VALUES('261','Tópicos Interdisciplinares em Computação II','Interdisciplinar',36,'Lógica de Programação','nan');
INSERT INTO ucs VALUES('262','Tópicos Interdisciplinares em Computação III','Interdisciplinar',36,'Algoritmos e Estrutura de Dados I','nan');
INSERT INTO ucs VALUES('263','Tópicos Interdisciplinares em Computação IV','Interdisciplinar',36,'Algoritmos e Estrutura de Dados I','nan');
INSERT INTO ucs VALUES('264','Topologia Geral','Eletiva',72,'Matemática Discreta','nan');
INSERT INTO ucs VALUES('265','Transdução de Grandezas Biomédicas','Eletiva',72,'Circuitos Elétricos','IMPAR');
INSERT INTO ucs VALUES('266','Tratamentos Térmicos','Eletiva',36,'Materiais Metálicos','nan');
INSERT INTO ucs VALUES('267','Validação e Verificação de Software','Eletiva',72,'Engenharia de Software','IMPAR');
INSERT INTO ucs VALUES('268','Vidros, Vitrocerâmicos e Vidrados','Eletiva',72,'Materiais Cerâmicos','nan');
COMMIT;
