# Generated by Django 4.1 on 2022-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifespClasses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subjectID", models.AutoField(primary_key=True, serialize=False)),
                ("subjectName", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("chTotal", models.IntegerField()),
                ("requirements", models.CharField(max_length=300)),
                ("semesterAvailable", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Subjects",
        ),
    ]
